<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\images\headerlogo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\headerlogo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.12" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravoRides.Application\TravoRides.Application.csproj" />
    <ProjectReference Include="..\TravoRides.Domain\TravoRides.Domain.csproj" />
  </ItemGroup>

</Project>
